import type { SeedAttribute } from "./types";

const N = (key: string, label: string, labelAr: string, unit?: string): SeedAttribute => ({ key, label, labelAr, type: "NUMBER", unit });
const S = (key: string, label: string, labelAr: string, options: string[]): SeedAttribute => ({ key, label, labelAr, type: "SELECT", options });
const B = (key: string, label: string, labelAr: string): SeedAttribute => ({ key, label, labelAr, type: "BOOLEAN" });
const T = (key: string, label: string, labelAr: string): SeedAttribute => ({ key, label, labelAr, type: "TEXT", filterable: false });

/**
 * Filterable spec keys per category. Products seeded in these categories carry the same keys, units and
 * SELECT values so the storefront can build facets directly from `Material.specs`.
 */
export const categoryAttributes: Record<string, SeedAttribute[]> = {
  // ---- construction categories (existing)
  "cement-concrete": [N("strength_mpa", "Strength", "المقاومة", "MPa"), S("type", "Type", "النوع", ["OPC", "SRC", "White", "Ready Mix"]), N("weight_kg", "Bag weight", "وزن الكيس", "kg")],
  "steel-rebar": [N("diameter_mm", "Diameter", "القطر", "mm"), S("grade", "Grade", "الدرجة", ["B500B", "Grade 60", "S275", "S355"]), S("type", "Type", "النوع", ["Rebar", "Mesh", "Beam", "Hollow Section"])],
  "blocks-bricks": [N("thickness_cm", "Thickness", "السماكة", "cm"), S("type", "Type", "النوع", ["Hollow", "Solid", "Insulated", "AAC", "Clay", "Paver", "Kerb"])],
  "tiles-flooring": [S("material", "Material", "الخامة", ["Porcelain", "Ceramic", "Marble", "Granite", "Adhesive"]), S("finish", "Finish", "التشطيب", ["Matt", "Glossy", "Polished", "Honed"]), T("size_cm", "Size", "المقاس")],
  "paints-coatings": [N("volume_l", "Volume", "السعة", "L"), S("finish", "Finish", "التشطيب", ["Matt", "Silk", "Gloss", "Textured"]), S("base", "Base", "الأساس", ["Water", "Solvent", "Epoxy"])],
  plumbing: [N("size_mm", "Size", "المقاس", "mm"), S("material", "Material", "الخامة", ["PVC", "PPR", "HDPE", "Copper", "GI", "CPVC", "Stainless Steel", "PE"]), N("pressure_pn", "Pressure class", "فئة الضغط", "PN")],
  electrical: [N("size_mm2", "Conductor size", "مقطع الموصل", "mm²"), N("cores", "Cores", "عدد الأسلاك"), N("voltage_v", "Voltage", "الجهد", "V"), N("rating_a", "Current rating", "التيار المقنن", "A")],
  "insulation-waterproofing": [N("thickness_mm", "Thickness", "السماكة", "mm"), S("type", "Type", "النوع", ["XPS", "PU", "Rockwool", "Bitumen Membrane", "Cementitious", "Liquid"])],
  "gypsum-ceilings": [N("thickness_mm", "Thickness", "السماكة", "mm"), S("type", "Type", "النوع", ["Standard", "Moisture Resistant", "Fire Rated", "Mineral Fibre", "Plaster"])],
  hvac: [N("capacity_btu", "Capacity", "السعة", "BTU"), N("capacity_ton", "Capacity", "السعة", "ton"), S("refrigerant", "Refrigerant", "غاز التبريد", ["R410A", "R32", "R22", "R134a", "N/A"]), S("type", "Type", "النوع", ["Split", "Window", "Cassette", "Ducted", "VRF", "FCU", "Chiller", "AHU", "Fan", "Duct", "Diffuser", "Damper"]), B("inverter", "Inverter", "إنفرتر")],
  lighting: [N("power_w", "Power", "القدرة", "W"), N("lumens", "Luminous flux", "التدفق الضوئي", "lm"), N("color_temp_k", "Colour temperature", "درجة حرارة اللون", "K"), S("ip_rating", "IP rating", "درجة الحماية", ["IP20", "IP44", "IP54", "IP65", "IP66"])],
  "safety-ppe": [S("standard", "Standard", "المواصفة", ["EN 397", "EN 20471", "EN ISO 20345", "EN 388", "EN 166", "EN 149", "N/A"]), S("size", "Size", "المقاس", ["S", "M", "L", "XL", "XXL", "Universal"])],
  "tools-equipment": [N("power_w", "Power", "القدرة", "W"), N("voltage_v", "Voltage", "الجهد", "V"), B("cordless", "Cordless", "لاسلكي")],
  "generators-compressors-pumps": [N("kva", "Rating", "القدرة", "kVA"), N("power_kw", "Power", "القدرة", "kW"), S("fuel", "Fuel", "الوقود", ["Diesel", "Petrol", "Electric"])],
  "fire-safety": [N("capacity_kg", "Capacity", "السعة", "kg"), S("agent", "Agent", "مادة الإطفاء", ["Dry Powder", "CO2", "Foam", "Water", "N/A"]), N("size_inch", "Size", "المقاس", "inch")],
  "heavy-equipment": [N("operating_weight_kg", "Operating weight", "وزن التشغيل", "kg"), N("engine_kw", "Engine power", "قدرة المحرك", "kW")],
  "solar-energy": [N("power_w", "Power", "القدرة", "W"), N("capacity_kwh", "Storage", "سعة التخزين", "kWh"), N("voltage_v", "Voltage", "الجهد", "V")],
  "scaffolding-access": [N("height_m", "Working height", "ارتفاع العمل", "m"), N("load_kg", "Load capacity", "الحمولة", "kg")],
  "lifting-rigging": [N("capacity_ton", "Capacity", "الحمولة", "ton"), N("length_m", "Length", "الطول", "m")],
  "welding-fabrication": [N("current_a", "Current", "التيار", "A"), S("process", "Process", "طريقة اللحام", ["MMA", "MIG", "TIG", "Plasma", "Oxy-fuel"])],
  // ---- MRO / facility categories (new)
  "hvac-spare-parts": [S("part_type", "Part type", "نوع القطعة", ["Compressor", "Filter", "Thermostat", "Refrigerant", "Copper Pipe", "Motor", "Capacitor", "Contactor", "Coil", "Valve", "Insulation", "Pump", "Tool"]), N("capacity_ton", "Capacity", "السعة", "ton"), S("refrigerant", "Refrigerant", "غاز التبريد", ["R410A", "R32", "R22", "R134a", "R404A", "N/A"]), N("voltage_v", "Voltage", "الجهد", "V"), N("size_inch", "Size", "المقاس", "inch")],
  "pumps-motors-drives": [S("part_type", "Type", "النوع", ["Pump", "Motor", "VFD", "Bearing", "Belt", "Coupling", "Seal", "Accessory"]), N("power_kw", "Power", "القدرة", "kW"), N("head_m", "Head", "الارتفاع", "m"), N("flow_m3h", "Flow", "التدفق", "m³/h"), N("voltage_v", "Voltage", "الجهد", "V"), N("rpm", "Speed", "السرعة", "rpm")],
  "valves-fittings-flanges": [S("type", "Type", "النوع", ["Gate", "Ball", "Butterfly", "Check", "Globe", "Strainer", "PRV", "Solenoid", "Float", "Air Release", "Flange", "Fitting", "Bolt Set"]), N("size_inch", "Size", "المقاس", "inch"), S("material", "Material", "الخامة", ["Brass", "Bronze", "Cast Iron", "Ductile Iron", "Stainless Steel", "Carbon Steel", "GI", "PVC"]), N("pressure_bar", "Pressure rating", "الضغط", "bar"), S("connection", "Connection", "التوصيل", ["Threaded", "Flanged", "Wafer", "Lug", "Welded", "Grooved"])],
  "lubricants-chemicals": [S("type", "Type", "النوع", ["Engine Oil", "Hydraulic Oil", "Gear Oil", "Compressor Oil", "Grease", "Degreaser", "Descaler", "Coil Cleaner", "Coolant", "Penetrating", "Cleaner", "Cutting Fluid", "Rust Treatment", "ATF"]), N("volume_l", "Volume", "السعة", "L"), N("weight_kg", "Weight", "الوزن", "kg"), S("viscosity", "Viscosity grade", "درجة اللزوجة", ["5W-30", "10W-40", "15W-40", "80W-90", "ISO 32", "ISO 46", "ISO 68", "ISO 220", "NLGI 2", "N/A"])],
  "cleaning-janitorial": [S("type", "Type", "النوع", ["Machine", "Chemical", "Tool", "Trolley", "Bin"]), N("volume_l", "Volume", "السعة", "L"), N("capacity_l", "Tank capacity", "سعة الخزان", "L"), N("power_w", "Power", "القدرة", "W")],
  "facility-consumables": [S("type", "Type", "النوع", ["Tissue", "Soap", "Dispenser", "Battery", "Bulb", "Air Freshener", "Bag", "Disposable", "Electrical"]), N("pack_qty", "Pack quantity", "عدد العبوة", "pcs")],
  "pest-control-hygiene": [S("type", "Type", "النوع", ["Insecticide", "Rodenticide", "Termiticide", "Larvicide", "Trap", "Sprayer", "Fogger", "Bird Control", "Sanitiser"]), N("volume_l", "Volume", "السعة", "L"), T("active_ingredient", "Active ingredient", "المادة الفعالة"), N("coverage_m2", "Coverage", "التغطية", "m²")],
  "security-cctv": [S("type", "Type", "النوع", ["Camera", "NVR", "DVR", "Storage", "Access Control", "Barrier", "Intercom", "Alarm", "Screening"]), N("resolution_mp", "Resolution", "الدقة", "MP"), N("ir_range_m", "IR range", "مدى الرؤية الليلية", "m"), N("channels", "Channels", "عدد القنوات"), B("poe", "PoE", "تغذية عبر الشبكة")],
  "low-current-networking": [S("type", "Type", "النوع", ["Cable", "Fibre", "Patch Panel", "Connector", "Switch", "Rack", "WiFi", "Tool", "Accessory"]), S("category", "Cable category", "فئة الكابل", ["Cat5e", "Cat6", "Cat6A", "Fibre OM3", "Fibre OM4", "Fibre OS2", "N/A"]), N("ports", "Ports", "عدد المنافذ"), N("rack_u", "Rack units", "وحدات الراك", "U"), B("poe", "PoE", "تغذية عبر الشبكة"), N("length_m", "Length", "الطول", "m")],
  "fire-life-safety-spares": [S("type", "Type", "النوع", ["Smoke Detector", "Heat Detector", "Multi Sensor", "Beam Detector", "Gas Detector", "Call Point", "Sounder", "Emergency Light", "Exit Sign", "Panel Module", "Battery", "Power Supply", "Sprinkler Head", "Switch", "Hose", "Extinguisher Spare"]), B("addressable", "Addressable", "معنون"), N("voltage_v", "Voltage", "الجهد", "V"), N("battery_hours", "Battery autonomy", "مدة البطارية", "h")],
  "irrigation-landscaping": [S("type", "Type", "النوع", ["Drip", "Sprinkler", "Controller", "Sensor", "Valve", "Pump", "Filter", "Pipe", "Fertiliser", "Tool", "Plant"]), N("flow_lph", "Flow", "التدفق", "L/h"), N("size_mm", "Size", "المقاس", "mm"), N("zones", "Zones", "عدد المناطق"), N("radius_m", "Radius", "نصف القطر", "m")],
  "swimming-pool": [S("type", "Type", "النوع", ["Pump", "Filter", "Media", "Chlorinator", "Heater", "Light", "Chemical", "Cleaner", "Accessory"]), N("power_kw", "Power", "القدرة", "kW"), N("flow_m3h", "Flow", "التدفق", "m³/h"), N("weight_kg", "Weight", "الوزن", "kg")],
  "water-treatment-tanks": [S("type", "Type", "النوع", ["RO System", "Softener", "Filter", "Cartridge", "Membrane", "Chemical", "Dosing Pump", "UV", "GRP Tank", "PE Tank", "Stainless Tank", "Pump", "Accessory"]), N("capacity_l", "Capacity", "السعة", "L"), N("flow_m3h", "Flow", "التدفق", "m³/h"), N("capacity_gpd", "Capacity", "الإنتاجية", "GPD")],
  "signage-road-safety": [S("type", "Type", "النوع", ["Traffic Sign", "Safety Sign", "Barrier", "Road Paint", "Speed Bump", "Bollard", "Cone", "Delineator", "Reflector", "Mirror", "Electronic"]), S("material", "Material", "الخامة", ["Aluminium", "Rubber", "Plastic", "Steel", "Stainless Steel", "Concrete", "Vinyl", "Thermoplastic", "Glass"]), B("reflective", "Reflective", "عاكس"), T("size_cm", "Size", "المقاس")],
  "site-office-furniture": [S("type", "Type", "النوع", ["Workstation", "Desk", "Chair", "Locker", "Shelving", "Pallet Racking", "Cabinet", "Table", "Bed", "Workbench"]), N("width_cm", "Width", "العرض", "cm"), N("load_kg", "Load per level", "الحمولة", "kg"), S("material", "Material", "الخامة", ["Steel", "Wood", "MDF", "Plastic", "Mesh", "Fabric", "Glass"])],
  "workwear-uniforms": [S("type", "Type", "النوع", ["Coverall", "Shirt", "Trousers", "Jacket", "Uniform", "Shoes", "Accessory"]), S("size", "Size", "المقاس", ["S", "M", "L", "XL", "XXL", "Universal"]), S("material", "Material", "الخامة", ["Cotton", "Polycotton", "Polyester", "Nomex", "Leather", "PVC", "Denim", "Plastic"]), B("hi_vis", "Hi-vis", "عاكس"), B("fr_rated", "Flame resistant", "مقاوم للهب")],
  "packaging-material-handling": [S("type", "Type", "النوع", ["Pallet", "Stretch Film", "Strapping", "Trolley", "Pallet Truck", "Stacker", "Box", "Container", "Tape", "Conveyor", "Scale"]), N("load_kg", "Load capacity", "الحمولة", "kg"), S("material", "Material", "الخامة", ["Wood", "Plastic", "Steel", "Paper", "PP", "PET", "LDPE", "HDPE"])],
  "glass-aluminium-systems": [S("type", "Type", "النوع", ["Curtain Wall Profile", "Curtain Wall System", "Door", "Window", "Glass", "Partition", "Handrail", "Louver", "Skylight", "Accessory", "Sealant"]), N("thickness_mm", "Thickness", "السماكة", "mm"), S("finish", "Finish", "التشطيب", ["Powder Coated", "Anodised", "Mill", "Wood Grain", "Clear", "Tinted", "Reflective", "Frosted", "N/A"]), S("glass_type", "Glass type", "نوع الزجاج", ["Tempered", "Laminated", "Double Glazed", "Float", "Frosted", "Mirror", "Fire Rated", "N/A"])],
  "smart-building-bms": [S("type", "Type", "النوع", ["Controller", "Sensor", "Meter", "Actuator", "Gateway", "Thermostat", "Software", "Display", "Panel"]), S("protocol", "Protocol", "البروتوكول", ["BACnet", "Modbus", "KNX", "DALI", "LoRaWAN", "Zigbee", "M-Bus", "Wi-Fi", "Analogue", "Pulse"]), N("io_points", "I/O points", "نقاط الدخل/الخرج"), N("voltage_v", "Voltage", "الجهد", "V")],
  "elevator-escalator-spares": [S("type", "Type", "النوع", ["Door Operator", "Door Part", "Rope", "Belt", "Controller", "Inverter", "Encoder", "Button", "Panel", "Display", "Sensor", "Roller", "Buffer", "Step", "Handrail", "Chain", "Oil", "Traction Machine", "Rescue Device", "Cable"]), T("compatible", "Compatible with", "متوافق مع"), N("load_kg", "Rated load", "الحمولة", "kg"), N("length_m", "Length", "الطول", "m")],
  "generator-ups-spares": [S("type", "Type", "النوع", ["Battery", "UPS", "ATS", "Filter", "Service Kit", "AVR", "Controller", "Charger", "Radiator", "Alternator Part", "Starter", "Fuel Part", "Belt", "Heater", "Silencer", "Fuel Tank"]), N("capacity_kva", "Rating", "القدرة", "kVA"), N("capacity_ah", "Capacity", "السعة", "Ah"), N("voltage_v", "Voltage", "الجهد", "V"), N("rating_a", "Current rating", "التيار", "A")],
  "kitchen-laundry-equipment": [S("type", "Type", "النوع", ["Cooking", "Refrigeration", "Dishwashing", "Laundry", "Prep", "Ventilation", "Storage", "Serving", "Fire Suppression"]), N("power_kw", "Power", "القدرة", "kW"), N("capacity_l", "Capacity", "السعة", "L"), N("capacity_kg", "Capacity", "السعة", "kg"), N("width_cm", "Width", "العرض", "cm"), B("gas", "Gas fired", "يعمل بالغاز")],
  "equipment-rental": [S("equipment", "Equipment", "المعدة", ["Excavator", "Loader", "Dump Truck", "Roller", "Grader", "Dozer", "Crane", "Telehandler", "Scaffolding", "Access Platform", "Generator", "Lighting", "Compressor", "Cabin", "Forklift", "Truck", "Pump", "Attachment", "Welding", "HVAC"]), T("capacity", "Capacity", "السعة"), B("with_operator", "With operator", "مع مشغل"), N("min_days", "Minimum hire", "الحد الأدنى للتأجير", "days")],
  services: [S("service_type", "Service", "نوع الخدمة", ["Installation", "Testing & Commissioning", "Calibration", "Pest Control", "AC Maintenance", "Waste Removal", "Crane Hire", "Cleaning", "Inspection", "Repair", "Consulting", "Training"]), N("duration_hours", "Typical duration", "المدة التقريبية", "h"), N("team_size", "Team size", "عدد الفريق"), B("includes_materials", "Materials included", "شامل المواد"), B("certificate", "Certificate issued", "مع شهادة")],
  "industrial-electrical-automation": [S("type", "Type", "النوع", ["Contactor", "Relay", "Timer", "PLC", "HMI", "Power Supply", "Sensor", "Panel", "Enclosure", "Panel Accessory", "Breaker", "Fuse", "Isolator", "Soft Starter", "Capacitor Bank", "Push Button", "Indicator", "Transformer", "Cable Gland", "Meter"]), N("rating_a", "Current rating", "التيار المقنن", "A"), N("voltage_v", "Voltage", "الجهد", "V"), N("poles", "Poles", "عدد الأقطاب")],
  "abrasives-consumables": [S("type", "Type", "النوع", ["Cutting Disc", "Grinding Disc", "Flap Disc", "Saw Blade", "Sandpaper", "Drill Bit", "Core Bit", "Wire Brush", "Chisel"]), N("diameter_mm", "Diameter", "القطر", "mm"), N("grit", "Grit", "الخشونة"), N("pack_qty", "Pack quantity", "عدد العبوة", "pcs")],
  "office-supplies": [S("type", "Type", "النوع", ["Paper", "Toner", "Printer", "Stationery", "Filing", "Whiteboard", "Shredder", "Label", "Machine"]), N("pack_qty", "Pack quantity", "عدد العبوة", "pcs")],
  "waste-management": [S("type", "Type", "النوع", ["Skip", "Wheelie Bin", "Litter Bin", "Compactor", "Baler", "Composter", "Bags", "Recycling Station", "Hazmat", "Tool"]), N("capacity_l", "Capacity", "السعة", "L"), S("material", "Material", "الخامة", ["Steel", "Stainless Steel", "HDPE", "LDPE", "PP", "Polyester"]), B("wheels", "Wheeled", "بعجلات")],
  "compressed-air-pneumatics": [S("type", "Type", "النوع", ["Hose", "Tube", "Fitting", "FRL", "Dryer", "Filter", "Cylinder", "Valve", "Tank", "Tool", "Compressor"]), N("size_inch", "Size", "المقاس", "inch"), N("pressure_bar", "Pressure", "الضغط", "bar"), N("flow_lpm", "Flow", "التدفق", "L/min")],
  "hoses-seals-gaskets": [S("type", "Type", "النوع", ["Hose", "Fitting", "Gasket", "O-Ring Kit", "Seal", "Packing", "Expansion Joint", "Sealant", "Clamp"]), N("size_inch", "Size", "المقاس", "inch"), S("material", "Material", "الخامة", ["Rubber", "EPDM", "NBR", "FKM", "PTFE", "Silicone", "Graphite", "Stainless Steel", "PVC", "UHMWPE", "Aluminium", "Non-asbestos"]), N("pressure_bar", "Pressure", "الضغط", "bar"), N("temp_c", "Max temperature", "أقصى درجة حرارة", "°C")],
};
