import type { SeedCategory } from "./types";

/** MRO / O&M / facility-management categories added on top of the 32 construction categories in seed.ts. */
export const extraCategories: SeedCategory[] = [
  { slug: "hvac-spare-parts", name: "HVAC Spare Parts", nameAr: "قطع غيار التكييف والتبريد", icon: "🧊" },
  { slug: "pumps-motors-drives", name: "Pumps, Motors & Drives", nameAr: "المضخات والمحركات ومحولات التردد", icon: "⚙️" },
  { slug: "valves-fittings-flanges", name: "Valves, Fittings & Flanges", nameAr: "الصمامات والوصلات والفلنجات", icon: "🔧" },
  { slug: "lubricants-chemicals", name: "Lubricants & Industrial Chemicals", nameAr: "الزيوت والشحوم والكيماويات الصناعية", icon: "🛢️" },
  { slug: "cleaning-janitorial", name: "Cleaning & Janitorial", nameAr: "التنظيف ومستلزمات النظافة", icon: "🧹" },
  { slug: "facility-consumables", name: "Facility Consumables", nameAr: "مستهلكات المرافق", icon: "🧻" },
  { slug: "pest-control-hygiene", name: "Pest Control & Hygiene", nameAr: "مكافحة الآفات والتعقيم", icon: "🐜" },
  { slug: "security-cctv", name: "Security & CCTV", nameAr: "الأمن وكاميرات المراقبة", icon: "📹" },
  { slug: "low-current-networking", name: "Low-Current & Networking", nameAr: "التيار الخفيف والشبكات", icon: "🌐" },
  { slug: "fire-life-safety-spares", name: "Fire Alarm & Life Safety Spares", nameAr: "قطع غيار الإنذار والسلامة", icon: "🚨" },
  { slug: "irrigation-landscaping", name: "Irrigation & Landscaping Supplies", nameAr: "الري ومستلزمات الحدائق", icon: "💧" },
  { slug: "swimming-pool", name: "Swimming Pool Equipment", nameAr: "معدات المسابح", icon: "🏊" },
  { slug: "water-treatment-tanks", name: "Water Treatment & Tanks", nameAr: "معالجة المياه والخزانات", icon: "💦" },
  { slug: "signage-road-safety", name: "Signage & Road Safety", nameAr: "اللافتات وسلامة الطرق", icon: "🚧" },
  { slug: "site-office-furniture", name: "Site & Office Furniture", nameAr: "أثاث المواقع والمكاتب", icon: "🪑" },
  { slug: "workwear-uniforms", name: "Workwear & Uniforms", nameAr: "ملابس العمل والزي الموحد", icon: "👕" },
  { slug: "packaging-material-handling", name: "Packaging & Material Handling", nameAr: "التغليف ومناولة المواد", icon: "📦" },
  { slug: "glass-aluminium-systems", name: "Glass & Aluminium Systems", nameAr: "أنظمة الزجاج والألمنيوم", icon: "🪟" },
  { slug: "smart-building-bms", name: "Smart Building & BMS", nameAr: "المباني الذكية وأنظمة إدارة المباني", icon: "🏢" },
  { slug: "elevator-escalator-spares", name: "Elevator & Escalator Spares", nameAr: "قطع غيار المصاعد والسلالم المتحركة", icon: "⬆️" },
  { slug: "generator-ups-spares", name: "Generator & UPS Spares", nameAr: "قطع غيار المولدات وأنظمة UPS", icon: "🔋" },
  { slug: "kitchen-laundry-equipment", name: "Commercial Kitchen & Laundry Equipment", nameAr: "معدات المطابخ والمغاسل التجارية", icon: "🍽️" },
  { slug: "equipment-rental", name: "Equipment Rental", nameAr: "تأجير المعدات", icon: "📅" },
  { slug: "services", name: "Services & Maintenance Visits", nameAr: "الخدمات وزيارات الصيانة", icon: "🧑‍🔧" },
  { slug: "industrial-electrical-automation", name: "Industrial Electrical & Automation", nameAr: "الكهرباء الصناعية والأتمتة", icon: "🎛️" },
  { slug: "abrasives-consumables", name: "Abrasives & Tool Consumables", nameAr: "الصنفرة ومستهلكات العدد", icon: "🪚" },
  { slug: "office-supplies", name: "Office Supplies & Printing", nameAr: "الأدوات المكتبية والطباعة", icon: "🖨️" },
  { slug: "waste-management", name: "Waste Management & Recycling", nameAr: "إدارة النفايات وإعادة التدوير", icon: "♻️" },
  { slug: "compressed-air-pneumatics", name: "Compressed Air & Pneumatics", nameAr: "الهواء المضغوط والأنظمة الهوائية", icon: "💨" },
  { slug: "hoses-seals-gaskets", name: "Hoses, Seals & Gaskets", nameAr: "الخراطيم والحشيات ومانعات التسرب", icon: "🧷" },
];
