"""equipment_rental_basis

Revision ID: beb8a6ab0142
Revises: eba23981b2fe
Create Date: 2026-09-24 15:21:16.349106
"""
from alembic import op
import sqlalchemy as sa


revision = 'beb8a6ab0142'
down_revision = 'eba23981b2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_period', sa.String(length=10), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_offer_supplier_product_city'), type_='unique')
        batch_op.create_index(batch_op.f('ix_offers_rental_period'), ['rental_period'], unique=False)
        batch_op.create_unique_constraint('uq_offer_supplier_product_city_basis', ['supplier_id', 'product_id', 'city', 'rental_period'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_offer_supplier_product_city_basis', type_='unique')
        batch_op.drop_index(batch_op.f('ix_offers_rental_period'))
        batch_op.create_unique_constraint(batch_op.f('uq_offer_supplier_product_city'), ['supplier_id', 'product_id', 'city'])
        batch_op.drop_column('rental_period')

    # ### end Alembic commands ###
