"""supplier documents, disputes

Revision ID: eba23981b2fe
Revises: 9c28b95b60e1
Create Date: 2026-09-17 21:45:42.669910
"""
from alembic import op
import sqlalchemy as sa


revision = 'eba23981b2fe'
down_revision = '9c28b95b60e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_documents_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_disputes_order_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_created_at'))

    op.drop_table('disputes')
    with op.batch_alter_table('supplier_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_documents_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_documents_status'))

    op.drop_table('supplier_documents')
    # ### end Alembic commands ###
